"""empty message

Revision ID: 678eb1034d23
Revises: 
Create Date: 2019-11-27 23:24:49.701623

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '678eb1034d23'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blog_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=False),
    sa.Column('password', sa.String(length=256), nullable=False),
    sa.Column('icon', sa.String(length=128), nullable=True),
    sa.Column('duration', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blog_user')
    # ### end Alembic commands ###
