"""empty message

Revision ID: 6bb2a59b2edd
Revises: 678eb1034d23
Create Date: 2019-11-27 23:25:16.723611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bb2a59b2edd'
down_revision = '678eb1034d23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('blog_title', sa.String(length=128), nullable=False),
    sa.Column('blog_content', sa.String(length=4096), nullable=True),
    sa.Column('blog_author_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['blog_author_id'], ['blog_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blog')
    # ### end Alembic commands ###
